### ISSUE TITLE
Function not defined

### ISSUE THREAD

**Issue by Simonesien** [Gangerl/csv2html#1]
Hello!
I just downloaded your cool script and this error appeared on the screen:
```
user@computer:~$ ./csv2html some_csv_file.csv 
awk: ./csv2html: line 863: function strftime never defined
user@computer:~$
```
By the way there isn't a function called `strftime`. When I do `cat csv2html | grep strftime`, only the call for the function comes:
```
user@computer:~$ cat csv2html | grep strftime
	return strftime("%Y-%m-%d")
user@computer:~$ 
```
I'm not sure whether it is my fault, and I only haven't installed awk correctly, but I need your help. 
Thanks in advance, Simon

**Comment by Gangerl** [comment]
Please use gawk as your preferred AWK version. Perhaps you can do a "apt install gawk" - that should fix this.
